### ISSUE TITLE
dart:ffi

### ISSUE THREAD

**Issue by Zeug-9** [danrubel/zwave.dart#1]
hello is what dart: ffi can bring something more to this library ?

**Comment by guyluz11** [comment]
It looks like we have to move to ffi.
I am trying to create a pr for this package that will make it work again with the new dart version.

The migration is supposed to be easy from non-null safety to null safety using the migration tool 
https://dart.dev/null-safety/migration-guide#migration-tool 

But I am getting errors about native extension being deprecated 

```dart
6 analysis issues found:
  error • Dart native extensions are deprecated and aren’t available in Dart 2.15 at lib/port/rpi_zw_port.dart:7:8 • (use_of_native_extension)
  error • Native functions can only be declared in the SDK and code that is loaded through native extensions at lib/port/rpi_zw_port.dart:163:29 • (native_function_body_in_non_sdk_code)
  error • Native functions can only be declared in the SDK and code that is loaded through native extensions at lib/port/rpi_zw_port.dart:164:20 • (native_function_body_in_non_sdk_code)
  error • Native functions can only be declared in the SDK and code that is loaded through native extensions at lib/port/rpi_zw_port.dart:165:34 • (native_function_body_in_non_sdk_code)
  error • Native functions can only be declared in the SDK and code that is loaded through native extensions at lib/port/rpi_zw_port.dart:166:28 • (native_function_body_in_non_sdk_code)
  error • Native functions can only be declared in the SDK and code that is loaded through native extensions at lib/port/rpi_zw_port.dart:167:42 • (native_function_body_in_non_sdk_code)

The migration tool didn't start, due to analysis errors.

We recommend fixing the analysis issues before running `dart migrate`.
Alternatively, you can run `dart migrate --ignore-errors`, but you might
get erroneous migration suggestions.

```

https://dart.dev/tools/diagnostic-messages#use_of_native_extension

And now I don't have the time (and knowledge about ffi) to work on it, so maybe at another time.


Created a pr for that and currently this issue has (we can call it blocker or first process) and issue number #2 must be fixed before that one.

**Comment by guyluz11** [comment]
The package have moved to [null safty](https://github.com/danrubel/zwave.dart/commit/1dbadd0bea426ef61ab12e92f559ab8b9384366a)  

We need not to move to ffi 

![Screenshot_20221103-205813_Firefox](https://user-images.githubusercontent.com/9304740/199810511-98d2cd99-1dd5-4677-a121-bd43be3e72b7.jpg)

**Comment by danrubel** [comment]
Agreed, we need to move the native code access from the older `dart-ext:` mechanism
to the newer `dart:ffi` approach... https://dart.dev/guides/libraries/c-interop

This is not something I have investigated yet.

**Comment by danrubel** [comment]
Over the weekend I managed to update https://github.com/danrubel/rpi_gpio.dart to use `dart:ffi`.
I started with that simpler and easier to test package to get a feel for how to update the code.
Hopefully over the next several weeks I'll be able to do the same for this package.

**Comment by danrubel** [comment]
This package has been updated to use `dart:ffi` and now runs on Dart SDK 2.18
