### ISSUE TITLE
Add null safty support

### ISSUE THREAD

**Issue by guyluz11** [danrubel/zwave.dart#2]
It can be overwhelming to bring back the package with the old dart version so I am suggesting doing it in parts.

The first part is adding null safety support.

This can be done without conflict with ffi that is must be implemented from dart version 2.15.0 by compiling and migrating (using the null safety migration tool) using an older version.
https://dart.dev/null-safety/migration-guide#migration-tool

Old dart version can be downloaded from here
https://dart.dev/get-dart/archive

**Comment by guyluz11** [comment]
I am creating a smart home Hub to control smart devices from a lot of vendors.
Having support for zwave will sure be must to have for a lot of users.

**Comment by danrubel** [comment]
I've just published a new null-safe version of this package... https://pub.dev/packages/zwave
Please let me know how it goes.
