### ISSUE TITLE
pub.dev page missing some parts

### ISSUE THREAD

**Issue by guyluz11** [danrubel/zwave.dart#4]
Some information is missing from pub dev

![Screenshot_20221103-204416_Firefox](https://user-images.githubusercontent.com/9304740/199808483-a1385310-fd60-480e-8aa0-f06bd5c6d61e.jpg)

And

![Screenshot_20221103-204430_Firefox](https://user-images.githubusercontent.com/9304740/199808494-da9a2b14-c139-4917-98c8-a80c51df00c2.jpg)

**Comment by danrubel** [comment]
This is fixed as part of the latest release
